name: Build and Deploy Pathfinding Visualizer
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-pygbag:
    name: Build Pathfinding Visualizer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        run: |
          echo "Attempting to install pygbag"
          python -m pip install pygbag
          echo "Successfully installed pygbag"
          echo "Attempting to build the game"
          python -m pygbag --build $GITHUB_WORKSPACE/main.py
          echo "Successfully build the game and complied to WebAssembly"

  deploy-to-gh-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build-pygbag

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: boatnoah/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: build/web
